name: Generate Datas
on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Generate the snake animation SVG
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: shanaulakh29
          svg_out_path: github-contribution-grid-snake.svg

      # Publish the generated SVG to the output branch
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
